### ISSUE TITLE
Unable to build mongoose-crate with Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by gregmarr** [achingbrain/mongoose-crate#15]
Visual Studio 2015 Update 2 contains changes that are incompatible with mmmagic v0.3.  These incompatibilities have been fixed in mmmagic v0.4.

**Comment by NXTaar** [comment]
Got the same problem. It seems 2015 C++ compiler is to fancy for the package. Mongoose-crate also doesn't compile on node higher than v5.11 (on Windows, don't know about Mac and Linux). For me, the solution was to use node v5.11 and Visual Studio 2013 Professional

**Comment by achingbrain** [comment]
Hey, sorry - this dropped off my radar.  Can you please try with v1.0.11 - just published.

**Comment by gregmarr** [comment]
Just built fine for me.  We ended up using a different module instead, so I can't test that it works properly, but it did previously when I manually updated to v0.4.

Thanks.
