### ISSUE TITLE
"Error: Attachment has no path property"

### ISSUE THREAD

**Issue by smoebody** [achingbrain/mongoose-crate#16]
hi, i try to attach an image directly from an express request according to the example in the `Readme.md`, but it seems not to work since the `.attach()` method gives me the following error:

    Error: Attachment has no path property!

is this usage obsolete or is this a bug or am i doing something wrong? im not really familiar with express file uploads so it might be an issue on my side.

thanks in advance

**Comment by achingbrain** [comment]
Could you post some example code?

**Comment by smoebody** [comment]
its hard to create working example code. im using expressjs with swagger-tools. the uploaded file resides inside `req.files.attachment[0]` and `req.swagger.params.attachment`
my controller looks something like this:

```js
exports.post = function (req, res, next) {
	debug('response to image create');
	const placeId = req.swagger.params.placeId.value;
	const imageId = req.swagger.params.imageId.value;
	const attachment = req.swagger.params.attachment.value;

	Place.findById(placeId).populate('image').then(function (place) {
		if (!place) return res.type('application/json').status(404).end();

		place.image.attach(imageId, attachment.buffer, function (err) {
			if (err) return res.type('application/json').status(500).end();
			res.json();
		});
	});
};
```

what i can say is that there is no key `path` inside the attachment-object. available keys are:

    ["fieldname","originalname","encoding","mimetype","buffer","size"]

**Comment by smoebody** [comment]
ok, after investigating the code a little more i can say that there is no support for file buffers right now. so this won't fix. closing.

**Comment by achingbrain** [comment]
Ah, sorry for not responding.  No, there's no support for buffers as it means you're holding the file contents in memory which isn't very scalable.

**Comment by smoebody** [comment]
@achingbrain no worries. maybe i try to implement buffers support and give you a PR
