### ISSUE TITLE
Delete is not removing files from s3 bucket.

### ISSUE THREAD

**Issue by rgruesbeck** [achingbrain/mongoose-crate#4]
Hi, my image files are not being deleted along with the model.
my model and crate config look like this.
```javascript

var path = require('path');
var mongoose = require('mongoose');
var timestamps = require('mongoose-times');
var URLSlugs = require('mongoose-url-slugs');
var crate = require('mongoose-crate');
var S3 = require('mongoose-crate-s3');
var ImageMagick = require('mongoose-crate-imagemagick');
var Schema = mongoose.Schema;

var aws = require('../config/env').config().aws;

var crateConfig = {
  storage: new S3({
    key: aws.accessKeyId,
    secret: aws.secretAccessKey,
    bucket: aws.bucket,
    acl: 'public-read',
    region: aws.region,
    path: function(image) {
      return '/images/' + path.basename(image.path);
    }
  }),
  fields: {
    image: {
      processor: new ImageMagick({
        tmpDir: '/tmp/ImageMagick',
        formats: ['JPEG', 'GIF', 'PNG'],
        transforms: {
          original: {
            format: '.jpg'
          },
          medium: {
            resize: '640x480',
            format: '.jpg'
          },
          small: {
            resize: '320x240',
            format: '.jpg'
          }
        }
      })
    }
  }
};

var postsSchema = new Schema({
  title: { type:String, required:true },
  body: { type:String, required:true },
  author: { type:String, required:true },
  published: { type:Boolean, required:true, default:false }
});

postsSchema.plugin(timestamps);
postsSchema.plugin(URLSlugs('title', {update: true}));
postsSchema.plugin(crate, crateConfig);

mongoose.model('posts', postsSchema);

```

**Comment by achingbrain** [comment]
Closing due to lack of response.  @rgruesbeck please re-open if you come back to this.

**Comment by startupthekid** [comment]
I can also confirm this issue.

Here's my function for deleting a user:

     //delete an existing user
    function deleteUser(params) {
        var deferred = q.defer();
        var response = { "status": 200, "deleted": null };

        if (typeof params._id === 'undefined') {
            response.status = 400;
            response.deleted = "invalid user id";
            deferred.resolve(response);
        }
       else {
            User.findById(params._id, function (err, user) {
                if (err) {
                     response.status = 400;
                response.deleted = err;
                deferred.resolve(response);
            }
            else {
            	User.remove({'_id':params._id},function(err){
            		if(err){
            			response.status = 400;
            			response.deleted = err;
            		} else {
            			response.deleted = user;
            		}
            		deferred.resolve(response);
            	}); 
            } 
        });
    }
    
    return deferred.promise;
    }

My model is defined as:
    
    var userSchema = new mongoose.Schema({
        facebookId  : { type: String, default: "", unique: true },
        twitterId   : { type: String, default: "", unique: true },
        firstName   : { type: String, trim: true, required: true },
        lastName    : { type: String, trim: true, required: true },
        email       : { type: String, lowercase: true, trim: true, required: true, unique: true },
        username    : { type: String, lowercase: true, trim: true, required: true, unique: true },
        created     : { type: Date, default: Date.now },
        updated     : { type: Date, default: Date.now },
        posts       : [{ type: mongoose.Schema.ObjectId, ref : 'Posts' }],
        comments    : [{ type: mongoose.Schema.ObjectId, ref : 'Comments'}],
        lofts       : [{ type: mongoose.Schema.ObjectId, ref : 'Lofts', childPath: 'members'}],
        likedPosts  : [{ type: mongoose.Schema.ObjectId, ref: 'Posts'}]
    });

    userSchema.plugin(relationship, {relationshipPathName: 'lofts', triggerMiddleware: true})
    userSchema.plugin(deepPopulate, {});
    userSchema.plugin(crate, {
        storage: new S3({
            key: constants.AWS_KEY,
            secret: constants.AWS_SECRET,
            bucket: 'swoopy-loft',
            acl: 'public-read',
            path: function(attachment){
                return '/user/' + path.basename(attachment.path); 
            }
        }),
    fields: {
        image: {
            processor: new ImageMagick({
            tmpDir: '/tmp', // Where transformed files are placed before storage, defaults to os.tmpdir()
            formats: ['JPEG', 'GIF', 'PNG'], // Supported formats, defaults to ['JPEG', 'GIF', 'PNG', 'TIFF']
            transforms: {
                original: {
                    resize: '750x750',
                    format: '.png'
                },
                small: {
                  resize: '250x250',
                  format: '.png'
                },
                medium: {
                  resize: '500x500',
                  format: '.png'
                }
            }
          })
        }
    }
    });

When I make a call to my delete function, the model gets removed but the images remain on S3.
