### ISSUE TITLE
this.toObject is not defined

### ISSUE THREAD

**Issue by rtm** [achingbrain/mongoose-crate#9]
I am using crate with s3. When I do a `Upload.findById(this.params.id)` on the model I'm getting the error

    node_modules\mongoose-crate\lib\Crate.js:176
    var model = this.toObject()
                     ^
    TypeError: undefined is not a function
        at EventEmitter.<anonymous> (/home/project/node_modules\mongoose-crate\lib\Crate.js:176:22)

At this point in time, `this` seems to be the global object, it shows on the console as 

    { domain: null, _events: { init: [Function] }, _maxListeners: 0 }

My model is defined as follows:

    var uploadSchema = new Schema({
        user: { type: Schema.Types.ObjectId, ref: 'User' }
    });

    uploadSchema.plugin(Crate, {
        storage: new S3({
            ....
        }),
        fields: {
            file: {}
        }
    });

**Comment by rtm** [comment]
No joy.

**Comment by achingbrain** [comment]
Good stuff.
